version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
  - package-ecosystem: 'github-actions'
    directory: '/.github/build-action/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
