name: Analysis
on:
  pull_request:
  push:
    # don't run on packaging branches
    branches-ignore:
      - 'for-debian'
      - 'debian/**'
      - 'pristine-tar'
    paths:
      - '**'
      - '!doc/**'
      - '!**.md'

jobs:

  clang:
    runs-on: ubuntu-20.04
    container: debian:sid
    name: clang-analyzer
    steps:
      - name: install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get -y install git python3-yaml apache2-bin apache2-dev gnutls-bin libapr1-dev libgnutls28-dev pkg-config procps clang-10 clang-tools-10 libmsv-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      # For pull requests get the head of the branch, instead of a
      # temporary merge
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: find usable IPs for tests
        run: |
          echo "test_ips=$(python3 test/check_test_ips.py -H localhost)" >> ${GITHUB_ENV}
      - name: autoreconf
        run: autoreconf -fiv
      - name: configure
        run: scan-build-10 --use-cc=clang-10 ./configure --enable-msva TEST_IP="${test_ips}" APACHE_MUTEX=pthread
      - name: store config.log
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: scan-build-config-log
          path: config.log
      - name: make
        run: scan-build-10 -sarif -o sarif-output --use-cc=clang-10 make
      - name: find output directory
        run: |
          echo "SARIF_DIR=$(ls -d sarif-output/*)" >> ${GITHUB_ENV}
      - name: define CONTAINER_WORKSPACE
        run: |
          echo "CONTAINER_WORKSPACE=${PWD}" >> ${GITHUB_ENV}
      - name: upload SARIF results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ env.SARIF_DIR }}
          checkout_path: ${{ env.CONTAINER_WORKSPACE }}

  cppcheck:
    runs-on: ubuntu-20.04
    container: debian:sid
    name: cppcheck
    steps:
      - name: install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get -y install git python3-yaml apache2-bin apache2-dev gnutls-bin libapr1-dev libgnutls28-dev libmsv-dev pkg-config procps bear cppcheck
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: autoreconf
        run: autoreconf -fiv
      - name: configure
        run: ./configure APACHE_MUTEX=pthread
      - name: make and create compile_commands.json
        run: bear -- make -j4
      - name: cppcheck
        run: |
          cppcheck --project=compile_commands.json -DAF_UNIX=1 --enable=warning,style,unusedFunction --xml 2>cppcheck.xml
      - uses: airtower-luna/convert-to-sarif@v0.2.0
        with:
          tool: 'CppCheck'
          input_file: 'cppcheck.xml'
          sarif_file: 'cppcheck.sarif'
      - name: define CONTAINER_WORKSPACE
        run: |
          echo "CONTAINER_WORKSPACE=${PWD}" >> ${GITHUB_ENV}
      - name: upload SARIF results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'cppcheck.sarif'
          checkout_path: ${{ env.CONTAINER_WORKSPACE }}

  codeql:
    runs-on: ubuntu-20.04
    name: CodeQL
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-yaml apache2-bin apache2-dev gnutls-bin libapr1-dev libgnutls28-dev libmsv-dev pkg-config procps
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
