name: CI build
on:
  push:
    # don't run on packaging branches
    branches-ignore:
      - 'for-debian'
      - 'debian/**'
      - 'pristine-tar'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        container:
          - 'debian:buster'
          - 'debian:sid'
          - 'fedora:32'
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    name: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies (Debian)
        if: startsWith(matrix.container, 'debian')
        run: |
          apt-get update
          apt-get -y install python3-yaml apache2-bin apache2-dev curl gnutls-bin libapr1-dev libgnutls28-dev openssl pandoc pkg-config procps softhsm2
      - name: install dependencies (Fedora)
        if: startsWith(matrix.container, 'fedora')
        run: |
          dnf -y group install "C Development Tools and Libraries"
          dnf -y install curl gnutls-devel gnutls-utils httpd-devel iproute python3-pyyaml redhat-rpm-config softhsm
      - name: network overview
        run: |
          ip addr show
          cat /etc/hosts
      - name: autoreconf
        run: autoreconf -fiv
      - name: configure
        run: TEST_IP=127.0.0.1 APACHE_MUTEX=pthread ./configure
      - name: store config.log
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ${{ matrix.container }}-config-log
          path: config.log
      - name: make
        run: make
      - name: make check
        run: VERBOSE=1 make check
      - name: store Apache logs
        uses: actions/upload-artifact@v1
        if: failure() || cancelled()
        with:
          name: ${{ matrix.container }}-apache-logs
          path: test/logs/
      - name: store test log if cancelled
        uses: actions/upload-artifact@v1
        if: cancelled()
        with:
          name: ${{ matrix.container }}-test-log
          path: test/test-00_basic.log
      - name: make distcheck
        run: VERBOSE=1 make distcheck
